#%RAML 1.0
title: Push notifications API
version: v1
mediaType: application/json
baseUri: hb://push-notifications

types:
  Platforms:
    enum:
      - ios

  CreateNotificationToken:
    type: object
    properties:
      platform: Platforms
      app_name: string
      device_token: string
      user_id: string

  NotificationToken:
    type: object
    properties:
      token_id: string
      platform: Platforms
      app_name: string
      device_token: string
      user_id: string
      created_at:
        type: number
        format: long

  PushNotification:
    type: object
    properties:
      notification: Notification
      data?: object

  Notification:
    type: object
    properties:
      title: string
      body: string
      badge?:
        type: number
        format: int

/tokens/{token_id}:
  uriParameters:
    token_id: string
  put:
    body: CreateNotificationToken
    responses:
      200:
      201:

  delete:
    responses:
       204:

/users/{user_id}/notifications:
  uriParameters:
    user_id:
  post:
    body: PushNotification
